### ISSUE TITLE
深色模式探讨

### ISSUE THREAD

**Issue by supergem3000** [supergem3000/supergem3000.github.io#4]
期望：默认情况下可以跟随系统设置自动选择浅色/深色模式，但同时也支持用户手动修改浅色/深色模式。

# 	方案一（VitePress）

使用一个开关调节浅色/深色。在`html`标签设定`class`是否包含`dark`决定主题颜色。

CSS中只需定义`:root`、`:root.dark`两种情况即可。

在JavaScript代码中，分为`'auto'`、`'dark'`、`'light'`三个状态设置。

同时获取一个媒体查询监听器：

```javascript
const query = windows.watchMedia('(prefer-color-scheme: dark)')
query.onchange = (e) => { ... }
```

当监听到媒体查询颜色偏好变化时，根据状态设置决定`html`标签中的`class`。

> [Window.matchMedia() - Web API 接口参考 | MDN (mozilla.org)](https://developer.mozilla.org/zh-CN/docs/Web/API/Window/matchMedia)
>
> `matchMedia()`返回一个`MediaQueryList`对象，可以向其添加监听器。
>
> [MediaQueryList - Web API 接口参考 | MDN (mozilla.org)](https://developer.mozilla.org/zh-CN/docs/Web/API/MediaQueryList)
>
> MDN中写的`addListener()`和`removeListener()`方法在TypeScript Lib中被标记为deprecated，实践时需要额外思考。

> 可在VitePress仓库中查看VPSwitchAppearance.vue组件了解此方案的实现详情。

# 方案二（MDN）

提供一个下拉菜单栏，包括“跟随系统”、“浅色”、“深色”三个选项。在`html`标签中`class`分为`'auto'`、`'dark'`、`'light'`决定主题颜色。

CSS中需要为`:root.auto`、`:root.dark`、`:root.light`三种情况分别定义。

但是不需要方案一中的媒体查询监听，只需要点击菜单栏中三个选项为`html`标签添加不同的`class`即可。

# MDN方案实践

定义最一层，具体颜色变量：

```css
:root {
  --color-white: #ffffff;
  --color-black: #000000;
  --color-dark: #333333;
  --color-light: #dcdcdc;
}
```

定义第二层，三个模式场景颜色变量，如：

```css
/* 跟随系统模式 */
@media (prefers-color-scheme: light) {
  :root.auto {
    --color-background: var(--color-white);
    --color-text: var(--color-black)
  }
}
@media (prefers-color-scheme: dark) {
  :root.auto {
    --color-background: var(--color-dark);
    --color-text: var(--color-light)
  }
}
:root.auto {
  color-scheme: light dark;
}

/* 浅色主题模式 */
:root.light,
:root {
  --color-background: var(--color-white);
  --color-text: var(--color-black);
  color-scheme: light;
}

/* 深色主题模式 */
:root.dark {
  --color-background: var(--color-dark);
  --color-text: var(--color-light);
  color-scheme: dark;
}
```

设置颜色：

```css
body {
  background-color: var(--color-background);
  color: var(--color-text);
  transition: color 0.5s, background-color 0.5s;
}
```

# `color-scheme`属性的作用

前文使用了媒体查询，判断颜色偏好，并设定了主题颜色，看起来已经完成了深色模式的适配，`color-scheme`属性似乎没起到什么作用。但其实如果不指定`color-scheme`，还存在一些细节上的问题。

![未指定color-scheme时的深色模式](https://user-images.githubusercontent.com/45116842/181240091-5007a78a-2161-4997-891c-11e5e705bca9.png)

从上图可以看到，三个`button`仍然是白底黑字，与深色模式黑底白字的愿景仍不同。

`color-scheme`属性的作用是设定用户代理样式表（浏览器样式）的默认值，最新的浏览器已经给默认样式提供了深色模式，只需设定`color-scheme: dark;`即可将默认样式也设定为深色模式。

![指定color-scheme时的深色模式](https://user-images.githubusercontent.com/45116842/181240035-6f6a03d2-484c-4080-9c7e-6c25eec08195.png)

这次和谐多了。

> 此CSS属性对浏览器版本要求还蛮高：(Edge 81, Firefox 96, Safari 13, Chrome 81, Opera 68)。

## 与`prefers-color-scheme`的区别

可以理解为主动与被动的区别。

`prefers-color-scheme`用来获得浏览器的颜色偏好，根据偏好由开发者设计样式。

`color-scheme`让开发者设置浏览器内置样式表的颜色模式。

> [CSS Color-Scheme 和深色模式-51CTO.COM](https://developer.51cto.com/article/713389.html)
>
> [使用 color-scheme CSS 属性和相应元标记改进深色模式默认样式 (web.dev)](https://web.dev/i18n/zh/color-scheme/)
